import { useMemo, useState } from 'react'
import { setCatalogVariantActive, updateCatalogClassification, type AdminCatalogRow } from '../lib/admin'

export function CatalogManagementAdmin({ catalog, onChanged }: { catalog: AdminCatalogRow[]; onChanged: () => Promise<void> }) {
  const [search, setSearch] = useState('')
  const [includeInactive, setIncludeInactive] = useState(false)
  const [drafts, setDrafts] = useState<Record<string, { family: string; subfamily: string }>>({})
  const [busy, setBusy] = useState('')
  const [message, setMessage] = useState('')
  const normalized = search.trim().toLowerCase()
  const rows = useMemo(() => normalized.length < 3 ? [] : catalog.filter((row) => (includeInactive || row.active) && [row.sku, row.producto, row.variante, row.familia, row.subfamilia].some((value) => value.toLowerCase().includes(normalized))).slice(0, 60), [catalog, includeInactive, normalized])
  const draftFor = (row: AdminCatalogRow) => drafts[row.product_id] ?? { family: row.familia, subfamily: row.subfamilia }
  const refresh = async (text: string) => { setMessage(text); await onChanged() }
  return <section className="admin-section stack catalog-management"><div><h2>Productos y categorías</h2><p className="muted">Buscá por nombre o SKU. La categoría se modifica para el producto; cada presentación puede ocultarse o restaurarse por separado.</p></div><div className="catalog-admin-search"><input type="search" aria-label="Buscar producto para administrar" placeholder="Escribí al menos 3 letras o un SKU" value={search} onChange={(event) => setSearch(event.target.value)} /><label><input type="checkbox" checked={includeInactive} onChange={(event) => setIncludeInactive(event.target.checked)} /> Ver desactivados</label></div>{normalized.length < 3 ? <p className="pending-control">Ingresá al menos 3 caracteres.</p> : rows.length === 0 ? <p className="pending-control">No se encontraron productos.</p> : <div className="catalog-admin-list">{rows.map((row) => { const draft = draftFor(row); return <article key={row.variant_id} className={!row.active ? 'inactive' : ''}><div className="catalog-admin-identity"><strong>{row.producto}</strong><span>{row.sku} · {row.variante || row.unidad}</span></div><label>Familia<input value={draft.family} onChange={(event) => setDrafts((current) => ({ ...current, [row.product_id]: { ...draft, family: event.target.value } }))} /></label><label>Subfamilia<input value={draft.subfamily} onChange={(event) => setDrafts((current) => ({ ...current, [row.product_id]: { ...draft, subfamily: event.target.value } }))} /></label><button disabled={busy === row.product_id || (draft.family === row.familia && draft.subfamily === row.subfamilia)} onClick={async () => { setBusy(row.product_id); try { await updateCatalogClassification(row.product_id, draft.family, draft.subfamily); await refresh(`Categoría de ${row.producto} guardada.`) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo guardar.') } finally { setBusy('') } }}>Guardar categoría</button><button className={row.active ? 'danger-outline' : 'secondary'} disabled={busy === row.variant_id} onClick={async () => { setBusy(row.variant_id); try { await setCatalogVariantActive(row.variant_id, !row.active); await refresh(row.active ? `${row.sku} se ocultó del cotizador.` : `${row.sku} volvió al cotizador.`) } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cambiar el estado.') } finally { setBusy('') } }}>{row.active ? 'Desactivar' : 'Restaurar'}</button></article> })}</div>}{message && <div className="policy-message" role="status">{message}</div>}</section>
}
