import { useEffect, useMemo, useState } from 'react'
import { createCommercialRule, loadCommercialRules } from '../lib/commercialRules'
import { DEFAULT_PAYMENT_POLICIES, loadPaymentPolicies, savePaymentPolicy, type PaymentPolicy } from '../lib/paymentPolicies'
import type { AdminCatalogRow } from '../lib/admin'

export function CommercialPolicyAdmin({ catalog, userEmail }: { catalog: AdminCatalogRow[]; userEmail: string }) {
  const families = useMemo(() => [...new Set(catalog.map((r) => r.familia).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'es-AR')), [catalog])
  const [ruleCount, setRuleCount] = useState(0), [payments, setPayments] = useState<PaymentPolicy[]>(DEFAULT_PAYMENT_POLICIES), [message, setMessage] = useState('')
  const [form, setForm] = useState({ family: '', comparator: 'gte' as 'gt' | 'gte', min: 1, net: 0, currency: 'USD' as 'USD' | 'ARS', unit: 'unidad', source: '', validFrom: new Date().toISOString().slice(0, 10) })
  useEffect(() => { loadCommercialRules().then((x) => setRuleCount(x.filter((r) => r.status === 'confirmado').length)); loadPaymentPolicies().then(setPayments) }, [])
  const selectedFamily = form.family || families[0] || ''
  useEffect(() => { if (!form.family && families[0]) window.setTimeout(() => setForm((value) => ({ ...value, family: families[0] })), 0) }, [families, form.family])
  const saveRule = async () => { try { await createCommercialRule({ scope_type: 'family', family: selectedFamily, variant_id: null, pack_group: null, quantity_comparator: form.comparator, min_quantity: form.min, net_amount: form.net, vat_rate: .21, currency: form.currency, unit: form.unit, valid_from: form.validFrom, valid_until: null, source: form.source, notes: '', aggregate_by_family: false, aggregate_by_pack_group: false }, userEmail); setRuleCount((v) => v + 1); setMessage('Regla creada como nueva versión auditable.') } catch (e) { setMessage(e instanceof Error ? e.message : 'No se pudo guardar.') } }
  const updatePayment = (id: string, field: keyof PaymentPolicy, value: string | number) => setPayments((xs) => xs.map((x) => x.id === id ? { ...x, [field]: value } : x))
  const penosilMissing = catalog.filter((r) => r.marca.toLowerCase() === 'penosil' && r.precio_mayorista === '')
  return <>
    <section className="admin-section stack"><div><h2>Políticas mayoristas</h2><p className="muted">Penosil: desde USD 1.800 netos + IVA, mezclando cajas de cualquier producto. Para otras familias creá reglas por cantidad sin sobrescribir el historial.</p></div><div className="policy-health"><strong>Penosil</strong><span>USD 1.800 netos · cajas combinables</span><b>{penosilMissing.length ? `${penosilMissing.length} SKU sin precio mayorista` : 'Lista completa'}</b></div>{penosilMissing.length > 0 && <details><summary>Ver SKU pendientes</summary><div className="pending-skus">{penosilMissing.slice(0, 100).map((r) => <span key={r.sku}>{r.sku} · {r.producto}</span>)}</div></details>}<div className="policy-form"><label>Familia<select value={form.family} onChange={(e) => setForm({ ...form, family: e.target.value })}>{families.map((x) => <option key={x}>{x}</option>)}</select></label><label>Condición<select value={form.comparator} onChange={(e) => setForm({ ...form, comparator: e.target.value as 'gt' | 'gte' })}><option value="gte">Desde</option><option value="gt">Más de</option></select></label><label>Cantidad<input type="number" min=".01" value={form.min} onChange={(e) => setForm({ ...form, min: Number(e.target.value) })} /></label><label>Precio neto<input type="number" min="0" step=".0001" value={form.net} onChange={(e) => setForm({ ...form, net: Number(e.target.value) })} /></label><label>Moneda<select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value as 'USD' | 'ARS' })}><option>USD</option><option>ARS</option></select></label><label>Unidad<input value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} /></label><label className="wide">Fuente / aprobación<input value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })} placeholder="Quién confirmó y cuándo" /></label></div><div className="admin-actions"><button disabled={!form.family || form.min <= 0 || form.net <= 0 || !form.source.trim()} onClick={saveRule}>Crear regla</button><span className="muted">{ruleCount} reglas confirmadas</span></div></section>
    <section className="admin-section stack"><div><h2>Formas de pago</h2><p className="muted">El texto y los ajustes se aplican al elegir la condición.</p></div><div className="payment-policy-list">{payments.map((p) => <article key={p.id}><input aria-label={`Nombre ${p.id}`} value={p.name} onChange={(e) => updatePayment(p.id, 'name', e.target.value)} /><input aria-label={`Texto ${p.id}`} value={p.customerText} onChange={(e) => updatePayment(p.id, 'customerText', e.target.value)} /><label>Dto. %<input type="number" value={p.discountPercent} onChange={(e) => updatePayment(p.id, 'discountPercent', Number(e.target.value))} /></label><label>Recargo %<input type="number" value={p.surchargePercent} onChange={(e) => updatePayment(p.id, 'surchargePercent', Number(e.target.value))} /></label><button onClick={async () => { try { await savePaymentPolicy(p); setMessage(`Condición “${p.name}” guardada.`) } catch (e) { setMessage(e instanceof Error ? e.message : 'Aplicá primero la migración.') } }}>Guardar</button></article>)}</div></section>{message && <div className="policy-message" role="status">{message}</div>}
  </>
}
